CREATE TABLE [dbo].[Patient]
(
	[User_Id] INT NOT NULL PRIMARY KEY,
	[PhoneNumber] VARBINARY(50) NOT NULL,
	[Adress] VARBINARY(128) NOT NULL,
	[BirthDate] VARBINARY(32) NOT NULL,
	[MedicalInfo] VARBINARY(2048) NOT NULL,

	CONSTRAINT [FK_Patient_User_Id] FOREIGN KEY ([User_Id])
			REFERENCES [User]([Id]) ON DELETE CASCADE
)
