CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL IDENTITY PRIMARY KEY,
	[Firstname] NVARCHAR(50)NOT NULL , 
	[Lastname] NVARCHAR(50)NOT NULL , 
	[Email] NVARCHAR(320) NOT NULL,
	[Password] NVARCHAR(255) NOT NULL, 
	[Role_Id] INT DEFAULT 1, 
	CONSTRAINT [FK_Role_Id] FOREIGN KEY ([Role_Id]) REFERENCES [Role]([Id]) ON DELETE SET NULL
)
